sudo: required

services:
  - docker
  
before_install:
- wget https://github.com/openshift/origin/releases/download/v1.3.1/openshift-origin-server-v1.3.1-dad658de7465ba8a234a4fb40b5b446a45a4cee1-linux-64bit.tar.gz -O openshift.tar.gz
- tar -xvf openshift.tar.gz -C ${pwd}
- ls -lar
- sudo ./openshift start

script:
- bundle exec rake test

